### ISSUE TITLE
ICD-10 API

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/icd-10-api#1]
### 📦 Describe the Goal
As a user, I would like to be able to search diagnoeses based on the icd-10 terminology. When entering a new diagnose, I want to simultaneously  get a list with matching suggestions. In the current solution these suggestions are just based on simple string comparison.
The ICD-10 API should include the following features and improvements:
- fuzzy search instead of strict string comparison
- search for matches not only in the icd title but also in meta data (such as icd field "inclusion", containing related diseases and synonyms)
- allow searching for icd10 codes instead of text only
- allow searching for multiple terms - regardless of their order
- filter best matches based on scoring and ranking 

### 🚚 Steps Towards this Goal
To achieve this goal, the following stories have to be completed:
- [x] setup new microservice
- [x] #3 - converting icd10-gm.json into FHIR Codesystem and preprocessing of data
- [x] #2 - implement search algorithm including the features mentioned above
- [x] #4 - implement scoring and ranking of matches
